import type { SQLiteDatabase } from "expo-sqlite";
import { EXERCISES, COMBAT_EXERCISES } from "../constants/exercises";

const TRAINING_DAY_EXERCISES: Record<
  string,
  {
    id: string;
    training_day_id: string;
    exercise_id: string;
    phase: string;
    position: number;
    sets: number;
    reps: number | null;
    hold_seconds: number;
    rest_seconds: number;
    notes: string;
  }[]
> = {
  day1: [
    {
      id: "d1w1",
      training_day_id: "day1",
      exercise_id: "upward_dog",
      phase: "warmup",
      position: 1,
      sets: 3,
      reps: 10,
      hold_seconds: 0,
      rest_seconds: 30,
      notes: "",
    },
    {
      id: "d1w2",
      training_day_id: "day1",
      exercise_id: "downward_dog",
      phase: "warmup",
      position: 2,
      sets: 3,
      reps: 10,
      hold_seconds: 0,
      rest_seconds: 30,
      notes: "",
    },
    {
      id: "d1w3",
      training_day_id: "day1",
      exercise_id: "knee_to_chest_hug",
      phase: "warmup",
      position: 3,
      sets: 3,
      reps: 10,
      hold_seconds: 0,
      rest_seconds: 30,
      notes: "",
    },
    {
      id: "d1m1",
      training_day_id: "day1",
      exercise_id: "glute_bridge",
      phase: "main",
      position: 1,
      sets: 4,
      reps: 20,
      hold_seconds: 0,
      rest_seconds: 60,
      notes: "Squeeze hard at top, pause 1 sec",
    },
    {
      id: "d1m2",
      training_day_id: "day1",
      exercise_id: "bulgarian_split_squat",
      phase: "main",
      position: 2,
      sets: 4,
      reps: 12,
      hold_seconds: 0,
      rest_seconds: 90,
      notes: "",
    },
    {
      id: "d1m3",
      training_day_id: "day1",
      exercise_id: "donkey_kick",
      phase: "main",
      position: 3,
      sets: 3,
      reps: 20,
      hold_seconds: 0,
      rest_seconds: 45,
      notes: "",
    },
    {
      id: "d1m4",
      training_day_id: "day1",
      exercise_id: "fire_hydrant",
      phase: "main",
      position: 4,
      sets: 3,
      reps: 20,
      hold_seconds: 0,
      rest_seconds: 45,
      notes: "",
    },
    {
      id: "d1m5",
      training_day_id: "day1",
      exercise_id: "sumo_squat",
      phase: "main",
      position: 5,
      sets: 4,
      reps: 15,
      hold_seconds: 0,
      rest_seconds: 60,
      notes: "Wide stance, toes out — hits inner thighs",
    },
    {
      id: "d1m6",
      training_day_id: "day1",
      exercise_id: "hip_thrust",
      phase: "main",
      position: 6,
      sets: 4,
      reps: 20,
      hold_seconds: 0,
      rest_seconds: 60,
      notes: "Shoulders on sofa or bed edge",
    },
    {
      id: "d1c1",
      training_day_id: "day1",
      exercise_id: "glute_stretch",
      phase: "cooldown",
      position: 1,
      sets: 6,
      reps: 10,
      hold_seconds: 0,
      rest_seconds: 20,
      notes: "",
    },
    {
      id: "d1c2",
      training_day_id: "day1",
      exercise_id: "hamstring_90_90",
      phase: "cooldown",
      position: 2,
      sets: 6,
      reps: 10,
      hold_seconds: 0,
      rest_seconds: 20,
      notes: "",
    },
    {
      id: "d1c3",
      training_day_id: "day1",
      exercise_id: "knee_to_chest_supine",
      phase: "cooldown",
      position: 3,
      sets: 6,
      reps: 10,
      hold_seconds: 0,
      rest_seconds: 20,
      notes: "",
    },
  ],
  day2: [
    {
      id: "d2w1",
      training_day_id: "day2",
      exercise_id: "toe_touch",
      phase: "warmup",
      position: 1,
      sets: 3,
      reps: 10,
      hold_seconds: 0,
      rest_seconds: 30,
      notes: "",
    },
    {
      id: "d2w2",
      training_day_id: "day2",
      exercise_id: "mountain_climber",
      phase: "warmup",
      position: 2,
      sets: 3,
      reps: 10,
      hold_seconds: 0,
      rest_seconds: 30,
      notes: "",
    },
    {
      id: "d2w3",
      training_day_id: "day2",
      exercise_id: "knee_to_chest_hug",
      phase: "warmup",
      position: 3,
      sets: 3,
      reps: 10,
      hold_seconds: 0,
      rest_seconds: 30,
      notes: "",
    },
    {
      id: "d2m1",
      training_day_id: "day2",
      exercise_id: "pushup",
      phase: "main",
      position: 1,
      sets: 4,
      reps: 12,
      hold_seconds: 0,
      rest_seconds: 60,
      notes: "Chest and shoulders — keeps upper body toned, not bulky",
    },
    {
      id: "d2m2",
      training_day_id: "day2",
      exercise_id: "pike_pushup",
      phase: "main",
      position: 2,
      sets: 3,
      reps: 10,
      hold_seconds: 0,
      rest_seconds: 60,
      notes: "Shoulder definition",
    },
    {
      id: "d2m3",
      training_day_id: "day2",
      exercise_id: "diamond_pushup",
      phase: "main",
      position: 3,
      sets: 3,
      reps: 10,
      hold_seconds: 0,
      rest_seconds: 60,
      notes: "Triceps — keeps arms slim and toned",
    },
    {
      id: "d2m4",
      training_day_id: "day2",
      exercise_id: "table_row",
      phase: "main",
      position: 4,
      sets: 4,
      reps: 12,
      hold_seconds: 0,
      rest_seconds: 60,
      notes: "Back width creates waist illusion",
    },
    {
      id: "d2m5",
      training_day_id: "day2",
      exercise_id: "plank",
      phase: "main",
      position: 5,
      sets: 3,
      reps: null,
      hold_seconds: 45,
      rest_seconds: 60,
      notes: "",
    },
    {
      id: "d2m6",
      training_day_id: "day2",
      exercise_id: "hollow_body_hold",
      phase: "main",
      position: 6,
      sets: 3,
      reps: null,
      hold_seconds: 30,
      rest_seconds: 60,
      notes: "",
    },
    {
      id: "d2m7",
      training_day_id: "day2",
      exercise_id: "dead_bug",
      phase: "main",
      position: 7,
      sets: 3,
      reps: 10,
      hold_seconds: 0,
      rest_seconds: 45,
      notes: "Deep core — pulls waist in",
    },
    {
      id: "d2m8",
      training_day_id: "day2",
      exercise_id: "side_plank",
      phase: "main",
      position: 8,
      sets: 3,
      reps: null,
      hold_seconds: 30,
      rest_seconds: 45,
      notes: "Obliques = waist taper",
    },
    {
      id: "d2a1",
      training_day_id: "day2",
      exercise_id: "crunch",
      phase: "abs",
      position: 1,
      sets: 3,
      reps: 20,
      hold_seconds: 0,
      rest_seconds: 30,
      notes: "",
    },
    {
      id: "d2a2",
      training_day_id: "day2",
      exercise_id: "leg_raise",
      phase: "abs",
      position: 2,
      sets: 3,
      reps: 15,
      hold_seconds: 0,
      rest_seconds: 30,
      notes: "Lower abs, helps flatten stomach",
    },
    {
      id: "d2a3",
      training_day_id: "day2",
      exercise_id: "bicycle_crunch",
      phase: "abs",
      position: 3,
      sets: 3,
      reps: 20,
      hold_seconds: 0,
      rest_seconds: 30,
      notes: "",
    },
    {
      id: "d2a4",
      training_day_id: "day2",
      exercise_id: "reverse_crunch",
      phase: "abs",
      position: 4,
      sets: 3,
      reps: 15,
      hold_seconds: 0,
      rest_seconds: 30,
      notes: "Lower abs, safer on back than sit-ups",
    },
    {
      id: "d2a5",
      training_day_id: "day2",
      exercise_id: "dead_bug",
      phase: "abs",
      position: 5,
      sets: 3,
      reps: 10,
      hold_seconds: 0,
      rest_seconds: 30,
      notes: "",
    },
    {
      id: "d2a6",
      training_day_id: "day2",
      exercise_id: "hollow_body_hold",
      phase: "abs",
      position: 6,
      sets: 3,
      reps: null,
      hold_seconds: 30,
      rest_seconds: 30,
      notes: "",
    },
    {
      id: "d2a7",
      training_day_id: "day2",
      exercise_id: "side_plank",
      phase: "abs",
      position: 7,
      sets: 3,
      reps: null,
      hold_seconds: 30,
      rest_seconds: 30,
      notes: "",
    },
    {
      id: "d2c1",
      training_day_id: "day2",
      exercise_id: "upward_dog",
      phase: "cooldown",
      position: 1,
      sets: 3,
      reps: 10,
      hold_seconds: 0,
      rest_seconds: 20,
      notes: "",
    },
    {
      id: "d2c2",
      training_day_id: "day2",
      exercise_id: "downward_dog",
      phase: "cooldown",
      position: 2,
      sets: 3,
      reps: 10,
      hold_seconds: 0,
      rest_seconds: 20,
      notes: "",
    },
  ],
  day3: [
    {
      id: "d3w1",
      training_day_id: "day3",
      exercise_id: "hamstring_90_90",
      phase: "warmup",
      position: 1,
      sets: 6,
      reps: 10,
      hold_seconds: 0,
      rest_seconds: 20,
      notes: "",
    },
    {
      id: "d3w2",
      training_day_id: "day3",
      exercise_id: "glute_stretch",
      phase: "warmup",
      position: 2,
      sets: 6,
      reps: 10,
      hold_seconds: 0,
      rest_seconds: 20,
      notes: "",
    },
    {
      id: "d3m1",
      training_day_id: "day3",
      exercise_id: "jump_squat",
      phase: "main",
      position: 1,
      sets: 4,
      reps: 15,
      hold_seconds: 0,
      rest_seconds: 60,
      notes: "Explosive — builds glute power. Land soft.",
    },
    {
      id: "d3m2",
      training_day_id: "day3",
      exercise_id: "reverse_lunge",
      phase: "main",
      position: 2,
      sets: 4,
      reps: 12,
      hold_seconds: 0,
      rest_seconds: 60,
      notes: "",
    },
    {
      id: "d3m3",
      training_day_id: "day3",
      exercise_id: "single_leg_glute_bridge",
      phase: "main",
      position: 3,
      sets: 4,
      reps: 15,
      hold_seconds: 0,
      rest_seconds: 60,
      notes: "",
    },
    {
      id: "d3m4",
      training_day_id: "day3",
      exercise_id: "wall_sit",
      phase: "main",
      position: 4,
      sets: 3,
      reps: null,
      hold_seconds: 45,
      rest_seconds: 60,
      notes: "",
    },
    {
      id: "d3m5",
      training_day_id: "day3",
      exercise_id: "calf_raise",
      phase: "main",
      position: 5,
      sets: 3,
      reps: 25,
      hold_seconds: 0,
      rest_seconds: 45,
      notes: "Ankle-to-calf ratio matters for leg aesthetics",
    },
    {
      id: "d3m6",
      training_day_id: "day3",
      exercise_id: "donkey_kick_pulse",
      phase: "main",
      position: 6,
      sets: 3,
      reps: 15,
      hold_seconds: 0,
      rest_seconds: 45,
      notes: "",
    },
    {
      id: "d3c1",
      training_day_id: "day3",
      exercise_id: "knee_to_chest_supine",
      phase: "cooldown",
      position: 1,
      sets: 6,
      reps: 10,
      hold_seconds: 0,
      rest_seconds: 20,
      notes: "",
    },
    {
      id: "d3c2",
      training_day_id: "day3",
      exercise_id: "toe_touch",
      phase: "cooldown",
      position: 2,
      sets: 3,
      reps: 10,
      hold_seconds: 0,
      rest_seconds: 20,
      notes: "",
    },
  ],
  day4: [
    {
      id: "d4ci1",
      training_day_id: "day4",
      exercise_id: "mountain_climber",
      phase: "circuit",
      position: 1,
      sets: 3,
      reps: null,
      hold_seconds: 45,
      rest_seconds: 15,
      notes: "",
    },
    {
      id: "d4ci2",
      training_day_id: "day4",
      exercise_id: "pushup",
      phase: "circuit",
      position: 2,
      sets: 3,
      reps: null,
      hold_seconds: 45,
      rest_seconds: 15,
      notes: "",
    },
    {
      id: "d4ci3",
      training_day_id: "day4",
      exercise_id: "sumo_squat",
      phase: "circuit",
      position: 3,
      sets: 3,
      reps: null,
      hold_seconds: 45,
      rest_seconds: 15,
      notes: "",
    },
    {
      id: "d4ci4",
      training_day_id: "day4",
      exercise_id: "glute_bridge",
      phase: "circuit",
      position: 4,
      sets: 3,
      reps: null,
      hold_seconds: 45,
      rest_seconds: 15,
      notes: "",
    },
    {
      id: "d4ci5",
      training_day_id: "day4",
      exercise_id: "plank",
      phase: "circuit",
      position: 5,
      sets: 3,
      reps: null,
      hold_seconds: 45,
      rest_seconds: 15,
      notes: "",
    },
    {
      id: "d4a1",
      training_day_id: "day4",
      exercise_id: "crunch",
      phase: "abs",
      position: 1,
      sets: 3,
      reps: 20,
      hold_seconds: 0,
      rest_seconds: 30,
      notes: "",
    },
    {
      id: "d4a2",
      training_day_id: "day4",
      exercise_id: "leg_raise",
      phase: "abs",
      position: 2,
      sets: 3,
      reps: 15,
      hold_seconds: 0,
      rest_seconds: 30,
      notes: "Lower abs, helps flatten stomach",
    },
    {
      id: "d4a3",
      training_day_id: "day4",
      exercise_id: "bicycle_crunch",
      phase: "abs",
      position: 3,
      sets: 3,
      reps: 20,
      hold_seconds: 0,
      rest_seconds: 30,
      notes: "",
    },
    {
      id: "d4a4",
      training_day_id: "day4",
      exercise_id: "reverse_crunch",
      phase: "abs",
      position: 4,
      sets: 3,
      reps: 15,
      hold_seconds: 0,
      rest_seconds: 30,
      notes: "Lower abs, safer on back than sit-ups",
    },
    {
      id: "d4a5",
      training_day_id: "day4",
      exercise_id: "dead_bug",
      phase: "abs",
      position: 5,
      sets: 3,
      reps: 10,
      hold_seconds: 0,
      rest_seconds: 30,
      notes: "",
    },
    {
      id: "d4a6",
      training_day_id: "day4",
      exercise_id: "hollow_body_hold",
      phase: "abs",
      position: 6,
      sets: 3,
      reps: null,
      hold_seconds: 30,
      rest_seconds: 30,
      notes: "",
    },
    {
      id: "d4a7",
      training_day_id: "day4",
      exercise_id: "side_plank",
      phase: "abs",
      position: 7,
      sets: 3,
      reps: null,
      hold_seconds: 30,
      rest_seconds: 30,
      notes: "",
    },
    {
      id: "d4co1",
      training_day_id: "day4",
      exercise_id: "upward_dog",
      phase: "cooldown",
      position: 1,
      sets: 3,
      reps: 10,
      hold_seconds: 0,
      rest_seconds: 20,
      notes: "",
    },
    {
      id: "d4co2",
      training_day_id: "day4",
      exercise_id: "knee_to_chest_hug",
      phase: "cooldown",
      position: 2,
      sets: 3,
      reps: 10,
      hold_seconds: 0,
      rest_seconds: 20,
      notes: "",
    },
    {
      id: "d4co3",
      training_day_id: "day4",
      exercise_id: "toe_touch",
      phase: "cooldown",
      position: 3,
      sets: 3,
      reps: 10,
      hold_seconds: 0,
      rest_seconds: 20,
      notes: "",
    },
    {
      id: "d4co4",
      training_day_id: "day4",
      exercise_id: "downward_dog",
      phase: "cooldown",
      position: 4,
      sets: 3,
      reps: 10,
      hold_seconds: 0,
      rest_seconds: 20,
      notes: "",
    },
    {
      id: "d4co5",
      training_day_id: "day4",
      exercise_id: "knee_to_chest_supine",
      phase: "cooldown",
      position: 5,
      sets: 6,
      reps: 10,
      hold_seconds: 0,
      rest_seconds: 20,
      notes: "",
    },
    {
      id: "d4co6",
      training_day_id: "day4",
      exercise_id: "glute_stretch",
      phase: "cooldown",
      position: 6,
      sets: 6,
      reps: 10,
      hold_seconds: 0,
      rest_seconds: 20,
      notes: "",
    },
    {
      id: "d4co7",
      training_day_id: "day4",
      exercise_id: "mountain_climber",
      phase: "cooldown",
      position: 7,
      sets: 3,
      reps: 10,
      hold_seconds: 0,
      rest_seconds: 20,
      notes: "Slow, as a stretch",
    },
    {
      id: "d4co8",
      training_day_id: "day4",
      exercise_id: "hamstring_90_90",
      phase: "cooldown",
      position: 8,
      sets: 6,
      reps: 10,
      hold_seconds: 0,
      rest_seconds: 20,
      notes: "",
    },
  ],
};

export async function seedDatabase(db: SQLiteDatabase) {
  await db.withTransactionAsync(async () => {
    for (const ex of EXERCISES) {
      await db.runAsync(
        "INSERT OR IGNORE INTO exercises (id, name, muscle_group, category, exercise_type, is_timed, each_side, hold_seconds, default_sets, default_reps, default_rest_seconds, notes) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
        ex.id,
        ex.name,
        ex.muscle_group,
        ex.category,
        ex.type,
        ex.is_timed,
        ex.each_side,
        ex.hold_seconds,
        ex.default_sets,
        ex.default_reps,
        ex.default_rest_seconds,
        ex.notes,
      );
    }

    const { TRAINING_DAYS } = await import("../constants/schedule");
    for (const td of TRAINING_DAYS) {
      await db.runAsync(
        "INSERT OR IGNORE INTO training_days (id, name, focus, day_number) VALUES (?, ?, ?, ?)",
        td.id,
        td.name,
        td.focus,
        td.day_number,
      );
    }

    for (const [dayId, exercises] of Object.entries(TRAINING_DAY_EXERCISES)) {
      for (const ex of exercises) {
        await db.runAsync(
          "INSERT OR IGNORE INTO training_day_exercises (id, training_day_id, exercise_id, phase, position, sets, reps, hold_seconds, rest_seconds, notes) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
          ex.id,
          ex.training_day_id,
          ex.exercise_id,
          ex.phase,
          ex.position,
          ex.sets,
          ex.reps,
          ex.hold_seconds,
          ex.rest_seconds,
          ex.notes,
        );
      }
    }
  });
}

export async function seedCombatContent(db: SQLiteDatabase) {
  await db.withTransactionAsync(async () => {
    // Insert combat exercises (INSERT OR IGNORE for idempotency)
    for (const ex of COMBAT_EXERCISES) {
      await db.runAsync(
        "INSERT OR IGNORE INTO exercises (id, name, muscle_group, category, exercise_type, is_timed, each_side, hold_seconds, default_sets, default_reps, default_rest_seconds, notes) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
        ex.id,
        ex.name,
        ex.muscle_group,
        ex.category,
        ex.type,
        ex.is_timed,
        ex.each_side,
        ex.hold_seconds,
        ex.default_sets,
        ex.default_reps,
        ex.default_rest_seconds,
        ex.notes,
      );
    }

    // Insert combat training_days
    const { TRAINING_DAYS } = await import("../constants/schedule");
    const combatDays = TRAINING_DAYS.filter(
      (d) =>
        d.id === "combat_a" ||
        d.id === "combat_b" ||
        d.id === "combat_c" ||
        d.id === "combat_d",
    );
    for (const td of combatDays) {
      await db.runAsync(
        "INSERT OR IGNORE INTO training_days (id, name, focus, day_number) VALUES (?, ?, ?, ?)",
        td.id,
        td.name,
        td.focus,
        td.day_number,
      );
    }

    // Insert combat training_day_exercises
    const COMBAT_TRAINING_DAY_EXERCISES = getCombatTrainingDayExercises();
    for (const [dayId, exercises] of Object.entries(
      COMBAT_TRAINING_DAY_EXERCISES,
    )) {
      for (const ex of exercises) {
        await db.runAsync(
          "INSERT OR IGNORE INTO training_day_exercises (id, training_day_id, exercise_id, phase, position, sets, reps, hold_seconds, rest_seconds, notes) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
          ex.id,
          ex.training_day_id,
          ex.exercise_id,
          ex.phase,
          ex.position,
          ex.sets,
          ex.reps,
          ex.hold_seconds,
          ex.rest_seconds,
          ex.notes,
        );
      }
    }

    // Seed milestones
    const PHASE_1_MILESTONES = [
      { id: "shadowbox_5_rounds", label: "Shadowbox 5 full rounds without losing form" },
      { id: "pushups_25", label: "25+ push-ups" },
      { id: "pike_pushups_8_12", label: "8–12 pike push-ups" },
      { id: "plank_1_min", label: "1 minute plank" },
      { id: "jump_squats_20", label: "20 jump squats" },
      { id: "stable_stance", label: "Fighter stance feels automatic" },
      { id: "mechanics_natural", label: "Jab / cross / hook mechanics feel natural" },
      { id: "body_recomp", label: "Visible body recomposition progress" },
    ];
    for (const m of PHASE_1_MILESTONES) {
      await db.runAsync(
        "INSERT OR IGNORE INTO milestones (id, label, completed) VALUES (?, ?, 0)",
        m.id,
        m.label,
      );
    }
  });
}

function getCombatTrainingDayExercises(): Record<
  string,
  {
    id: string;
    training_day_id: string;
    exercise_id: string;
    phase: string;
    position: number;
    sets: number;
    reps: number | null;
    hold_seconds: number;
    rest_seconds: number;
    notes: string;
  }[]
> {
  return {
    combat_a: [
      // WARMUP
      { id: "caw1", training_day_id: "combat_a", exercise_id: "jump_rope", phase: "warmup", position: 1, sets: 3, reps: null, hold_seconds: 120, rest_seconds: 30, notes: "" },
      { id: "caw2", training_day_id: "combat_a", exercise_id: "fighter_stance", phase: "warmup", position: 2, sets: 1, reps: null, hold_seconds: 60, rest_seconds: 30, notes: "" },
      { id: "caw3", training_day_id: "combat_a", exercise_id: "footwork_basic", phase: "warmup", position: 3, sets: 2, reps: null, hold_seconds: 60, rest_seconds: 30, notes: "" },
      // MAIN
      { id: "cam1", training_day_id: "combat_a", exercise_id: "stance_mirror", phase: "main", position: 1, sets: 1, reps: null, hold_seconds: 120, rest_seconds: 30, notes: "Film yourself. Look for chin, guard, knee bend." },
      { id: "cam2", training_day_id: "combat_a", exercise_id: "shadow_jab", phase: "main", position: 2, sets: 4, reps: 50, hold_seconds: 0, rest_seconds: 45, notes: "Controlled snap — no rush" },
      { id: "cam3", training_day_id: "combat_a", exercise_id: "shadow_cross", phase: "main", position: 3, sets: 4, reps: 30, hold_seconds: 0, rest_seconds: 45, notes: "Hip rotation drives every rep" },
      { id: "cam4", training_day_id: "combat_a", exercise_id: "shadow_jab_cross", phase: "main", position: 4, sets: 4, reps: 20, hold_seconds: 0, rest_seconds: 60, notes: "One combo = 1 rep. Full guard reset each time." },
      { id: "cam5", training_day_id: "combat_a", exercise_id: "shadowboxing", phase: "main", position: 5, sets: 3, reps: null, hold_seconds: 180, rest_seconds: 60, notes: "Jab and cross only this round — no hooks yet. Move feet." },
      // COOLDOWN
      { id: "cac1", training_day_id: "combat_a", exercise_id: "fighter_stance", phase: "cooldown", position: 1, sets: 1, reps: null, hold_seconds: 60, rest_seconds: 20, notes: "" },
      { id: "cac2", training_day_id: "combat_a", exercise_id: "footwork_basic", phase: "cooldown", position: 2, sets: 2, reps: null, hold_seconds: 60, rest_seconds: 20, notes: "" },
    ],
    combat_b: [
      // WARMUP
      { id: "cbw1", training_day_id: "combat_b", exercise_id: "jump_rope", phase: "warmup", position: 1, sets: 3, reps: null, hold_seconds: 120, rest_seconds: 30, notes: "" },
      { id: "cbw2", training_day_id: "combat_b", exercise_id: "footwork_basic", phase: "warmup", position: 2, sets: 3, reps: null, hold_seconds: 60, rest_seconds: 30, notes: "" },
      // MAIN
      { id: "cbm1", training_day_id: "combat_b", exercise_id: "footwork_circle", phase: "main", position: 1, sets: 3, reps: null, hold_seconds: 60, rest_seconds: 30, notes: "Circle a chair. Maintain stance the entire time." },
      { id: "cbm2", training_day_id: "combat_b", exercise_id: "footwork_pivot", phase: "main", position: 2, sets: 4, reps: 10, hold_seconds: 0, rest_seconds: 30, notes: "Lead foot pivot. Exit 45°." },
      { id: "cbm3", training_day_id: "combat_b", exercise_id: "footwork_step_jab", phase: "main", position: 3, sets: 4, reps: 15, hold_seconds: 0, rest_seconds: 45, notes: "Step first. Punch second. Never at the same time." },
      { id: "cbm4", training_day_id: "combat_b", exercise_id: "slip_drill", phase: "main", position: 4, sets: 3, reps: null, hold_seconds: 60, rest_seconds: 45, notes: "Small movement — head just outside the line, not exaggerated" },
      { id: "cbm5", training_day_id: "combat_b", exercise_id: "shadow_slip_jab", phase: "main", position: 5, sets: 3, reps: 10, hold_seconds: 0, rest_seconds: 45, notes: "Slip outside, jab immediately on the way back" },
      { id: "cbm6", training_day_id: "combat_b", exercise_id: "shadow_roll", phase: "main", position: 6, sets: 3, reps: 10, hold_seconds: 0, rest_seconds: 45, notes: "Knees bend, rotate under, come up in guard" },
      { id: "cbm7", training_day_id: "combat_b", exercise_id: "defense_shadow", phase: "main", position: 7, sets: 3, reps: null, hold_seconds: 180, rest_seconds: 60, notes: "Guard, slips, pulls, pivots only. No power punching." },
      // COOLDOWN
      { id: "cbc1", training_day_id: "combat_b", exercise_id: "footwork_basic", phase: "cooldown", position: 1, sets: 2, reps: null, hold_seconds: 60, rest_seconds: 20, notes: "" },
      { id: "cbc2", training_day_id: "combat_b", exercise_id: "fighter_stance", phase: "cooldown", position: 2, sets: 1, reps: null, hold_seconds: 60, rest_seconds: 20, notes: "" },
    ],
    combat_c: [
      // WARMUP
      { id: "ccw1", training_day_id: "combat_c", exercise_id: "jump_rope", phase: "warmup", position: 1, sets: 3, reps: null, hold_seconds: 120, rest_seconds: 30, notes: "" },
      { id: "ccw2", training_day_id: "combat_c", exercise_id: "footwork_basic", phase: "warmup", position: 2, sets: 2, reps: null, hold_seconds: 60, rest_seconds: 30, notes: "" },
      { id: "ccw3", training_day_id: "combat_c", exercise_id: "shadow_jab_cross", phase: "warmup", position: 3, sets: 2, reps: 15, hold_seconds: 0, rest_seconds: 30, notes: "" },
      // CIRCUIT
      { id: "ccc1", training_day_id: "combat_c", exercise_id: "combat_circuit_shadow", phase: "circuit", position: 1, sets: 3, reps: null, hold_seconds: 60, rest_seconds: 60, notes: "" },
      { id: "ccc2", training_day_id: "combat_c", exercise_id: "combat_circuit_mc", phase: "circuit", position: 2, sets: 3, reps: null, hold_seconds: 60, rest_seconds: 60, notes: "" },
      { id: "ccc3", training_day_id: "combat_c", exercise_id: "combat_circuit_squat", phase: "circuit", position: 3, sets: 3, reps: null, hold_seconds: 60, rest_seconds: 60, notes: "" },
      { id: "ccc4", training_day_id: "combat_c", exercise_id: "combat_circuit_pushup", phase: "circuit", position: 4, sets: 3, reps: null, hold_seconds: 60, rest_seconds: 60, notes: "" },
      { id: "ccc5", training_day_id: "combat_c", exercise_id: "combat_circuit_plank", phase: "circuit", position: 5, sets: 3, reps: null, hold_seconds: 60, rest_seconds: 60, notes: "" },
      // MAIN
      { id: "ccm1", training_day_id: "combat_c", exercise_id: "shadow_hook", phase: "main", position: 1, sets: 3, reps: 15, hold_seconds: 0, rest_seconds: 45, notes: "Elbow level. Short arc. Not a swing." },
      { id: "ccm2", training_day_id: "combat_c", exercise_id: "shadow_body_hook", phase: "main", position: 2, sets: 3, reps: 10, hold_seconds: 0, rest_seconds: 45, notes: "Bend knees. Hook to the ribs." },
      { id: "ccm3", training_day_id: "combat_c", exercise_id: "shadow_jab_cross_hook", phase: "main", position: 3, sets: 3, reps: 10, hold_seconds: 0, rest_seconds: 60, notes: "Full 3-punch combo. Reset guard after each." },
      { id: "ccm4", training_day_id: "combat_c", exercise_id: "shadow_teep", phase: "main", position: 4, sets: 3, reps: 10, hold_seconds: 0, rest_seconds: 45, notes: "Knee first. Hips through. Recoil." },
      { id: "ccm5", training_day_id: "combat_c", exercise_id: "shadow_low_kick", phase: "main", position: 5, sets: 3, reps: 8, hold_seconds: 0, rest_seconds: 45, notes: "Rotate hips fully. Shin — not foot." },
      { id: "ccm6", training_day_id: "combat_c", exercise_id: "shadow_knee", phase: "main", position: 6, sets: 3, reps: 10, hold_seconds: 0, rest_seconds: 45, notes: "Hips forward. Strike upward." },
      { id: "ccm7", training_day_id: "combat_c", exercise_id: "shadowboxing", phase: "main", position: 7, sets: 3, reps: null, hold_seconds: 180, rest_seconds: 60, notes: "Use everything — jab, cross, hook, teep, knee. Move. Imagine." },
      // COOLDOWN
      { id: "ccc1c", training_day_id: "combat_c", exercise_id: "footwork_basic", phase: "cooldown", position: 1, sets: 2, reps: null, hold_seconds: 60, rest_seconds: 20, notes: "" },
      { id: "ccc2c", training_day_id: "combat_c", exercise_id: "fighter_stance", phase: "cooldown", position: 2, sets: 1, reps: null, hold_seconds: 60, rest_seconds: 20, notes: "" },
    ],
    combat_d: [
      // WARMUP
      { id: "cdw1", training_day_id: "combat_d", exercise_id: "jump_rope", phase: "warmup", position: 1, sets: 2, reps: null, hold_seconds: 120, rest_seconds: 30, notes: "" },
      { id: "cdw2", training_day_id: "combat_d", exercise_id: "footwork_basic", phase: "warmup", position: 2, sets: 2, reps: null, hold_seconds: 60, rest_seconds: 20, notes: "" },
      { id: "cdw3", training_day_id: "combat_d", exercise_id: "fighter_stance", phase: "warmup", position: 3, sets: 1, reps: null, hold_seconds: 60, rest_seconds: 20, notes: "" },
      // MAIN
      { id: "cdm1", training_day_id: "combat_d", exercise_id: "shadow_teep", phase: "main", position: 1, sets: 3, reps: 10, hold_seconds: 0, rest_seconds: 45, notes: "Knee lifts first. Hips push through. Recoil immediately." },
      { id: "cdm2", training_day_id: "combat_d", exercise_id: "shadow_low_kick", phase: "main", position: 2, sets: 3, reps: 8, hold_seconds: 0, rest_seconds: 45, notes: "Rotate hips fully. Swing shin not foot." },
      { id: "cdm3", training_day_id: "combat_d", exercise_id: "shadow_knee", phase: "main", position: 3, sets: 3, reps: 10, hold_seconds: 0, rest_seconds: 45, notes: "Thrust hips forward. Strike upward." },
      { id: "cdm4", training_day_id: "combat_d", exercise_id: "shadow_jab_cross_hook", phase: "main", position: 4, sets: 3, reps: 10, hold_seconds: 0, rest_seconds: 45, notes: "Mix it in — keep mechanics clean" },
      { id: "cdm5", training_day_id: "combat_d", exercise_id: "shadowboxing", phase: "main", position: 5, sets: 3, reps: null, hold_seconds: 180, rest_seconds: 60, notes: "Mix boxing and Muay Thai. Flow and visualize. Stay relaxed." },
      // COOLDOWN
      { id: "cdc1", training_day_id: "combat_d", exercise_id: "footwork_basic", phase: "cooldown", position: 1, sets: 1, reps: null, hold_seconds: 60, rest_seconds: 20, notes: "" },
      { id: "cdc2", training_day_id: "combat_d", exercise_id: "fighter_stance", phase: "cooldown", position: 2, sets: 1, reps: null, hold_seconds: 60, rest_seconds: 20, notes: "" },
    ],
  };
}
